# GCN (Graph Convolutional Network) with Global Coord Embedder
model_type: 'gcn'
description: 'Graph Convolutional Network - A Graph Convolutional Network model that uses graph convolution to learn graph structure.'

model_config:
  # common settings
  in_channels: 4
  hidden_channels: 16
  global_dim: 7
  out_dim: 1
  num_layers: 2
  use_edge_attr: false
  use_global_features: true
  coord_embed_method: 'spherical' # 'mlp', 'sinusoidal', 'distance_based', 'spherical'
  pooling_method: 'mean'
  activation_function: 'relu'
  dropout: 0.1
  edge_dim: 2
  edge_embedding_dim: 16
  user_global_coord_embedder: true
  
  
  # GCN specific
  special_config:
    normalize: true  # normalization
    add_self_loops: true  # self-loop
    bias: true  # bias
