# GraphSAGE - Variant 4
model_type: 'sage'
description: 'GraphSAGE - A GraphSAGE model that uses sampling-based graph learning.'

model_config:
  in_channels: 4
  hidden_channels: 96
  global_dim: 7
  out_dim: 1
  num_layers: 3
  use_edge_attr: true
  use_global_features: true
  coord_embed_method: 'distance_based'
  pooling_method: 'mean'
  activation_function: 'leaky_relu'
  dropout: 0.3
  edge_dim: 2
  edge_embedding_dim: 64
  user_global_coord_embedder: false
  

  # GraphSAGE specific
  special_config:
    normalize: false  # normalization
    root_weight: false  # root weight
    bias: false  # bias
    # Sampling size (each layer)
    sample_sizes: [8, 4, 2]  # sampling size for each layer
