# GraphSAGE - Variant 3
model_type: 'sage'
description: 'GraphSAGE - A GraphSAGE model that uses sampling-based graph learning.'

model_config:
  in_channels: 4
  hidden_channels: 128
  global_dim: 7
  out_dim: 1
  num_layers: 4
  use_edge_attr: true
  use_global_features: true
  coord_embed_method: 'sinusoidal'
  pooling_method: 'add'
  activation_function: 'gelu'
  dropout: 0.0
  edge_dim: 2
  edge_embedding_dim: 8
  user_global_coord_embedder: false
  

  # GraphSAGE specific
  special_config:
    normalize: true  # normalization
    root_weight: true  # root weight
    bias: true  # bias
    # Sampling size (each layer)
    sample_sizes: [15, 10, 5, 2]  # sampling size for each layer
